/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DBModel;
import model.IModel;

/**
 *
 * @author nagyg
 */
public class Foablak extends javax.swing.JFrame {

    private IModel model;//a modelt berakjuk adattagba, így a conn kapcsolatot is el tudjuk érni a főablak osztályon belül
    //bármilyen más osztályból is el tudjuk érni, ha átadjuk annak az osztálynak, így lehet az összes DBModel metódusat használni, a close-t is

    public Foablak() {
        initComponents();

        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//a Frame-nek van egy ilyen metódusa, semmit ne csináljon, ha az x-re kattintok
        addWindowListener(new WindowAdapter() {//alt+ins,override methode
            @Override
            public void windowClosing(WindowEvent e) {
                sajatClose();
            }

        });

        setLocationRelativeTo(null);
        setTitle("Megrendelők és megrendeléseik nyílvántartása");

        String dbUser = "root";
        String dbPass = "1234";
        String dbURL = "jdbc:mysql://localhost:3306/megrendelesek";

        try {
            Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPass);
            model = new DBModel(conn);//csinált egy model objectumot, nyitott egy adatbázis kapcsolatot
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.toString(), "Adatbázis hiba",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    public void sajatClose() {
        if (model != null) {//ha van modelünk
            try {
                model.close();//bezárja az adatbázis kapcsolatot

            } catch (SQLException ex) {
                hibaAblak(ex.toString());
            }
        }
        System.exit(0);//kilépünk a programból
    }

    public static void hibaAblak(String hiba) {
        JOptionPane.showMessageDialog(null, hiba, "Hiba történt",//itt a rootPane vagy a null= a parent
                JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mbFajl = new javax.swing.JMenu();
        miKilepes = new javax.swing.JMenuItem();
        mbAdatok = new javax.swing.JMenu();
        miSzemelyek = new javax.swing.JMenuItem();
        miMegrendeles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mbFajl.setText("Fájl");
        mbFajl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        miKilepes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miKilepes.setText("Kilépés");
        miKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKilepesActionPerformed(evt);
            }
        });
        mbFajl.add(miKilepes);

        jMenuBar1.add(mbFajl);

        mbAdatok.setText("Adatok");
        mbAdatok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        miSzemelyek.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miSzemelyek.setText("Személy");
        miSzemelyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSzemelyekActionPerformed(evt);
            }
        });
        mbAdatok.add(miSzemelyek);

        miMegrendeles.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miMegrendeles.setText("Megrendelés");
        miMegrendeles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMegrendelesActionPerformed(evt);
            }
        });
        mbAdatok.add(miMegrendeles);

        jMenuBar1.add(mbAdatok);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSzemelyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSzemelyekActionPerformed
        SzemelyekDialog szd = new SzemelyekDialog(this, true, model);//this:parentet kér, az a Frame=this, az őt létrehozó szülő; modális:true
        szd.setVisible(true);
    }//GEN-LAST:event_miSzemelyekActionPerformed

    private void miKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKilepesActionPerformed
        sajatClose();
    }//GEN-LAST:event_miKilepesActionPerformed

    private void miMegrendelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMegrendelesActionPerformed
        MegrendelesekDialog md = new MegrendelesekDialog(this, true, model);
        md.setVisible(true);
    }//GEN-LAST:event_miMegrendelesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mbAdatok;
    private javax.swing.JMenu mbFajl;
    private javax.swing.JMenuItem miKilepes;
    private javax.swing.JMenuItem miMegrendeles;
    private javax.swing.JMenuItem miSzemelyek;
    // End of variables declaration//GEN-END:variables
}
