/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import model.IModel;
import model.Rendeles;
import model.Szemely;

/**
 *
 * @author nagyg
 */
public class MegrendelesAdatokDialog extends javax.swing.JDialog {
    
    private java.awt.Frame parent;
    private boolean mentes;
    private Rendeles rendeles;
    private Szemely szemely;
    private List<Szemely> szemelyek;
    
    public MegrendelesAdatokDialog(java.awt.Frame parent, List<Szemely> szemelyek, Szemely kivalasztott) {
        //fentről kitöröltem és az őshívásban megadjuk h true, mindig az lesz, így is lehet
        super(parent, true);
        initComponents();
        mentes = false;
        this.parent = parent;

        //feltöltöm az összes elemmel
        cbMegrendelo.setModel(new DefaultComboBoxModel<>(szemelyek.toArray(new Szemely[0])));
        //átveszem hogy mi legyen a kiválasztott személy
        cbMegrendelo.setSelectedItem(kivalasztott);
        
        setLocationRelativeTo(parent);
        setTitle("Új megrendelés felvétele");
    }
    
    public boolean isMentes() {
        return mentes;
    }
    
    public Rendeles getRendeles() {
        return rendeles;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbMegrendelo = new javax.swing.JComboBox<>();
        tfOsszeg = new javax.swing.JTextField();
        tfDarabszam = new javax.swing.JTextField();
        chekbTeljesitve = new javax.swing.JCheckBox();
        btnMegsem = new javax.swing.JButton();
        btnMentes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Megrendelő:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Összeg:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Darabszám:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Teljesítve:");

        cbMegrendelo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfOsszeg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfDarabszam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        chekbTeljesitve.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chekbTeljesitve.setPreferredSize(new java.awt.Dimension(21, 21));

        btnMegsem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMegsem.setText("Mégsem");
        btnMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegsemActionPerformed(evt);
            }
        });

        btnMentes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMentes.setText("Mentés");
        btnMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMegsem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addComponent(btnMentes))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chekbTeljesitve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDarabszam, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfOsszeg, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbMegrendelo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 337, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMegrendelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfOsszeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDarabszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(chekbTeljesitve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMegsem)
                    .addComponent(btnMentes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegsemActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnMegsemActionPerformed

    private void btnMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMentesActionPerformed
        
        Szemely szemely = (Szemely) cbMegrendelo.getSelectedItem();
        if (szemely != null) {//csak ha ki van választva vki akkor csinálom a többit
            try {
                rendeles = new Rendeles();
                
                rendeles.setRendeloId(szemely.getId());
                rendeles.setDarabszam(Integer.parseInt(tfDarabszam.getText()));
                rendeles.setOsszeg(Integer.parseInt(tfOsszeg.getText()));
                rendeles.setTeljesitve(chekbTeljesitve.isSelected());
                
                mentes = true;
                setVisible(false);
            } catch (NumberFormatException ex) {
                Foablak.hibaAblak("Kérlek csak egész számot adj meg");
            }
        } else {
            Foablak.hibaAblak("Válasszon ki egy személyt");
        }
        
    }//GEN-LAST:event_btnMentesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMegsem;
    private javax.swing.JButton btnMentes;
    private javax.swing.JComboBox<Szemely> cbMegrendelo;
    private javax.swing.JCheckBox chekbTeljesitve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfDarabszam;
    private javax.swing.JTextField tfOsszeg;
    // End of variables declaration//GEN-END:variables
}
